# Generated by Django 5.0.6 on 2024-06-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0002_biodata_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodata',
            options={'verbose_name_plural': '1.Biodata'},
        ),
    ]
