# Generated by Django 5.0.6 on 2024-06-21 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0003_alter_artikel_options_alter_kategori_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
